* Proof of Concept, Work will start soon!

Graphica is a mathematical animations engine, which is inspired by [[https://github.com/3b1b/manim][manim]]. But, manim is a python library, which works fine given the scripting-language nature of python.
Graphica is purely an /engine for achieving visualisation of mathematical problems/. Say you want to visualise a 3 dimensional graph, but in a more quirky way, graphica has got you covered.

I am a mathematics nerd who has for long been using manim, but I feel certain limitations with it, especially since its written in python. Therefore, I am creating this project to learn more about programming and mathematics and,
to perhaps make a manim alternative which makes sense to me.

** How does it work?

Graphica is not a full-scale application. It is not a geogebra clone. It still is upholds the programmatic way of animating math that manim implements, but in a different way.

Long story short, it uses lua bindings for all the functions that graphica implements, making you, the programmer-math-nerd-abomination a little less sleep deprived.
Fennel support should also work out of the box, courtesy of me being a lisp nerd.

** Implementation.

Basically it's Rust-made manim with lua bindings. /This entire document was definetely not a social experiment to see how long you can read this mess./ Most of graphica's design and implementation is inspired by manim,
but it takes due advantage of rust's capabilities and some /saner(?)/ design choices and aims to achieve the following:

**** 1. Smooth, orgasm-inducing animations thanks to Vulkan
**** 2. Concurrency for complex animations
**** 3. Cool Parallelisation support with Nvidia CUDA (Track the CUDA branch for that build, but dont expect much work on it now.)
**** 4. Integration with Lua and to make the writing experience far superior to that of manim

** Warning!

This is a purely hobbyist project which is by no means meant to be used for serious work in any form, this is not even alpha stage software at its best. And work can truly only be expected to start from my side in a year or two.
